name: flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

  # QR Code Generator
  qr_flutter: ^4.0.0

  # PDF / Drucken
  pdf: ^3.10.4
  printing: ^5.12.0

  # JS‑Interop für Web (Pflicht für PWA‑Install)
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
